INSERT INTO addresses (cep, state, city, neighbourhood, number, complement, reference) VALUES ('96419266', 'RS', 'Bagé', 'Habitar Brasil', '1432', 'Ap 403', 'Prédio azul')
INSERT INTO addresses (cep, state, city, neighbourhood, number, complement, reference) VALUES ('55640103', 'PE', 'GVila Real', 'Mieira', '221', '', 'Casa verde' )
INSERT INTO addresses (cep, state, city, neighbourhood, number, complement, reference) VALUES ('15054616', 'SP', 'São Joaquim','São José', '543', 'Sobrado', 'Casa azul' )
INSERT INTO addresses (cep, state, city, neighbourhood, number, complement, reference) VALUES ('60745050', 'RO', 'Porto Velho', 'Artur Lundgren', '2345', 'Travesa', '' )
INSERT INTO addresses (cep, state, city, neighbourhood, number, complement, reference) VALUES ('29138065', 'ES', 'Viana', 'Cassino', '623', 'Ap 802 B', 'Na frente dos Correios' )
INSERT INTO addresses (cep, state, city, neighbourhood, number, complement, reference) VALUES ('84020710', 'AC', 'Rio Branco', 'Piranga', '324', '', 'Na frente ao bar do Zeca' )
INSERT INTO addresses (cep, state, city, neighbourhood, number, complement, reference) VALUES ('29178038', 'ES', 'Serra', 'Jardim', '522', 'Fundos', 'Casa cinza' )
INSERT INTO addresses (cep, state, city, neighbourhood, number, complement, reference) VALUES ('69036100', 'AM', 'Manaus', 'Ponta Negra', '5623', 'Ap 201', 'Prédio verde e branco' )
INSERT INTO addresses (cep, state, city, neighbourhood, number, complement, reference) VALUES ('57044137', 'AL', 'Maceió', 'São Jorge', '253', '', 'Casa amarela' )
INSERT INTO addresses (cep, state, city, neighbourhood, number, complement, reference) VALUES ('68902130', 'AP', 'MAcapá', 'Arruda', '734', 'Ap 303', '' )
