INSERT INTO payments_status (description) VALUES ('Aguardando Pagamento')
INSERT INTO payments_status (description) VALUES ('Em atraso')
INSERT INTO payments_status (description) VALUES ('Pagamento Efetuado')
INSERT INTO payments_status (description) VALUES ('Pagamento confirmado')
INSERT INTO payments_status (description) VALUES ('Cancelado')
INSERT INTO payments_status (description) VALUES ('Reembolsado')
INSERT INTO payments_status (description) VALUES ('Erro de pagamento')
INSERT INTO payments_status (description) VALUES ('Pagamento em analise')
INSERT INTO payments_status (description) VALUES ('Realizado em outra plataforma')
INSERT INTO payments_status (description) VALUES ('Pagamento agendado')
INSERT INTO payments_status (description) VALUES ('Pagamento parcial')

