INSERT INTO payments_methods (description) VALUES ('Cartao de Credito')
INSERT INTO payments_methods (description) VALUES ('Cartao de Debito')
INSERT INTO payments_methods (description) VALUES ('Dinheiro')
INSERT INTO payments_methods (description) VALUES ('Convenio')
INSERT INTO payments_methods (description) VALUES ('TED')
INSERT INTO payments_methods (description) VALUES ('Pix')
INSERT INTO payments_methods (description) VALUES ('Boleto Bancario')
INSERT INTO payments_methods (description) VALUES ('Cheque')
INSERT INTO payments_methods (description) VALUES ('Cartao de Saude')
INSERT INTO payments_methods (description) VALUES ('Parcelamento')
