INSERT INTO db_fisio_oficial.dbo.services (description, price) VALUES ('Acupuntura',                         120)
INSERT INTO db_fisio_oficial.dbo.services (description, price) VALUES ('Reeducacao Postural Global',         150)
INSERT INTO db_fisio_oficial.dbo.services (description, price) VALUES ('Pilates Terapeutico',                130)
INSERT INTO db_fisio_oficial.dbo.services (description, price) VALUES ('Liberacao Miofascial',               95) 
INSERT INTO db_fisio_oficial.dbo.services (description, price) VALUES ('Termoterapia',                       70)
INSERT INTO db_fisio_oficial.dbo.services (description, price) VALUES ('Laserterapia',                       110)
INSERT INTO db_fisio_oficial.dbo.services (description, price) VALUES ('Ultrassom Terapeutico',              90)
INSERT INTO db_fisio_oficial.dbo.services (description, price) VALUES ('Eletroterapia',                      120)
INSERT INTO db_fisio_oficial.dbo.services (description, price) VALUES ('Cinesioterapia',                     100)
INSERT INTO db_fisio_oficial.dbo.services (description, price) VALUES ('Massagem Terapeutica',               80)
INSERT INTO db_fisio_oficial.dbo.services (description, price) VALUES ('Avaliacao',                          55)
INSERT INTO db_fisio_oficial.dbo.services (description, price) VALUES ('Treinamento de marcha e mobilidade', 85)
INSERT INTO db_fisio_oficial.dbo.services (description, price) VALUES ('Gerenciamento da dor',               90)