INSERT INTO SERVICES (description, price) VALUES ('Acupuntura',                 120)
INSERT INTO SERVICES (description, price) VALUES ('Reeducação Postural Global', 150)
INSERT INTO SERVICES (description, price) VALUES ('Pilates Terapêutico',        130)
INSERT INTO SERVICES (description, price) VALUES ('Liberação Miofascial',       95) 
INSERT INTO SERVICES (description, price) VALUES ('Termoterapia',               70)
INSERT INTO SERVICES (description, price) VALUES ('Laserterapia',               110)
INSERT INTO SERVICES (description, price) VALUES ('Ultrassom Terapêutico',      90)
INSERT INTO SERVICES (description, price) VALUES ('Eletroterapia',              120)
INSERT INTO SERVICES (description, price) VALUES ('Cinesioterapia',             100)
INSERT INTO SERVICES (description, price) VALUES ('Massagem Terapêutica',       80)