export enum ScheduleStatus {
  SCHEDULED = 2,
  IN_PROGRESS = 3,
  COMPLETED = 4,
  ON_HOLD = 9,
  DID_NOT_ATTEND = 10,
  RESCHEDULED = 11,
  DELAYED = 12,
  AWAITING_CONFIRMATION = 13,
  CANCELED_BY_CLINIC = 14,
  CANCELED_BY_CLIENT = 15,
}
